version: 0.2

phases:
  pre_build:
    commands:
      - npm i
      - npm install -g @ionic/cli
  build:
    commands:
      - npm run build:prod
artifacts:
  files:
    - '**/*'
  base-directory: www